# redis
redis:
  image: redis
  ports:
    - "6379:6379"
# hubot
hubot:
  build: .
  links:
    - redis:redis
  environment:
    REDIS_URL: http://redis:6379
  ports:
    - "8080:8080"
  env_file: .env

